#!/usr/bin/env python3

import argparse
import sys

import commands

utilDescription = 'hashup: a utility to work with hashdeep files'

parser = argparse.ArgumentParser(description=utilDescription)
subparsers = parser.add_subparsers(required=True, title='commands', description='available commands', help='additional')

parser_diff = subparsers.add_parser('diff', help='show logical differences in files')
parser_diff.add_argument('reference', help='the original "benchmark" file')
parser_diff.add_argument('compare', help='the file to check against the benchmark')
parser_diff.set_defaults(func=commands.diff)

parser_diff = subparsers.add_parser('info', help='print generic information about the hashdeep file')
parser_diff.add_argument('file', help='a hashdeep output file')
parser_diff.add_argument('-f', '--format', default='csv', help='hashdeep format: one of {csv}')
parser_diff.set_defaults(func=commands.info)

if len(sys.argv)==1:
    parser.print_help(sys.stderr)
    sys.exit(1)

args = parser.parse_args()
#print('args:', args);
args.func(args)
